# Generated by Django 4.1.6 on 2023-08-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(blank=True, default='education', max_length=50, null=True),
        ),
    ]
